FIXED 116 Hard crash destroying Joshaberry Bush due to missing berryseed.
Terasology/SimpleFarming pull request #117
Opened 2021-07-11 23:13 UTC by NicolaasJKotze

berryseed added to atlas. The game would hard crash when destroying a Joshaberry Bush due to missing berryseed reference.

### Bug:
https://github.com/Terasology/SimpleFarming/issues/116

### Known Issue(s):
After destroying a Joshaberry Bush, its seed will be invisible/transparent and not visible to the player if it is on the
ground. However, when having collected 2 or more, a number will appear in the inventory and when hovered over the name will be displayed.
When planting the berry bush seed it will take much longer than other bushes to grow.

### Test Configuration(s):
displayVersion=alpha-20
engineVersion=5.1.0-SNAPSHOT
Java: 11.0.11 in C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
Java VM: OpenJDK 64-Bit Server VM, version: 11.0.11+9
OS: Windows 8.1, arch: amd64, version: 6.3
GFX: nVidia GTX 1050Ti Driver 471.11
SimpleFarming-2.2.0-SNAPSHOT

2021-07-12 18:22 UTC, jdrueckert requested changes
Please also add a texture to the [texture atlas](https://github.com/Terasology/SimpleFarming/blob/develop/assets/textures/SimpleFarming.png), otherwise the item will be invisible in-game as the field you added to the atlas definition will point to an "empty" part of the texture atlas.
It's sufficient if you simply copy the first texture in the texture atlas.

2021-07-12 23:46 UTC, NicolaasJKotze commented
Updated. Everything was a minor text change in the atlas.

2021-07-13 17:21 UTC, jdrueckert requested changes
Please also adjust the occurrence of `TestBerrySeed` in `assets/prefabs/Testing/TestSeed.prefab` accordingly

2021-07-17 18:37 UTC, jdrueckert approved these changes

2021-07-17 18:37 UTC, merged